'use client';
import {useEffect,useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';

type Bet={game_id:string;player_id:string;player:string;team:string;opponent:string;side:string;line:number;book:string;odds:number;mean:number;p_model:number;p_market:number;p_final:number;ev:number;robust_ev?:number|null;bet_to:number;status:string;reasons:string[];kickoff:string;source_url:string;observed_at:string;other_books?:number;interval80?:number[];expected_margin?:number;game_total?:number;model_weight?:number;warnings?:string[];scenario_means?:{underdog_7:number;pickem:number;favorite_7:number};native_reasons?:string[];shared_safety_reasons?:string[]};
type Performance={bets:number;settled:number;units:number;roi:number|null;clv_bets?:number;mean_clv?:number|null};
type Forecast={mean:number;p_over:number;p_push:number};
type Pair={game_id:string;player_id:string;player:string;team:string;book:string;line:number;kickoff:string;champion:Forecast;challenger:Forecast};
type Metrics={mae:number|null;brier:number|null;log_loss:number|null};
type Challenger={status:string;model_version:string;recommendations:Bet[];watchlist:Bet[];source_errors?:string[];metadata?:Record<string,unknown>;performance?:Performance};
type Board={generated_at:string;status:string;slate:string;quotes:number;players:number;recommendations:Bet[];watchlist:Bet[];source_errors:string[];validation?:{chosen:string;holdout_2025:{mae:number;coverage_80:number};baseline_2025:{mae:number}};performance?:Performance;model_version:string;challenger?:Challenger;comparison?:{paired_forecasts:Pair[];performance:{champion:Performance;challenger:Performance};forecast_metrics:{n_total:number;n_settled:number;n_probability_scored:number;champion:Metrics;challenger:Metrics};historical_benchmark?:{n:number;astra:{mae:number;rmse:number};claude:{mae:number;rmse:number};claude_minus_astra_mae_95ci:number[]}}};
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const odds=(n:number)=>n>0?`+${n}`:String(n);
const spread=(n:number)=>n===0?'PK':`${n>0?'+':''}${n}`;
const date=(d:string)=>new Date(d).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const value=(n:number|null|undefined,digits=3)=>n==null?'—':n.toFixed(digits);
const source='https://github.com/drhyphy/nfl-qb-attempts';

function ModelPanel({kind,model,now,suspended}:{kind:'champion'|'challenger';model:{recommendations:Bet[];watchlist:Bet[];status:string};now:number;suspended:boolean}){
 const claude=kind==='challenger';const failed=model.status==='source_failure'||model.status==='error'||model.status==='unavailable'||model.status==='stale'||model.status==='stale_history';
 const active=model.recommendations.filter(b=>new Date(b.kickoff).getTime()>now);const blocked=suspended||failed;
 return <>
 <div className="sectiontitle"><h2>{claude?'Claude Fable challenger':'Codex V2 champion'} recommendations</h2><span>{claude?'Ranked by estimated EV · original model policy':'Ranked by stressed expected return'}</span></div>
 {blocked||!active.length?<div className="empty"><span className="emptytag">{blocked?'RECOMMENDATIONS SUSPENDED':'NO QUALIFYING BETS'}</span><h3>{failed?'Challenger evaluation unavailable.':blocked?'Waiting for a fresh evaluation.':'Waiting for a price worth taking.'}</h3><p>{failed?'The champion can continue independently. A previous challenger card is never reused as a new decision.':'Held candidates remain visible below. An empty card is part of the record.'}</p></div>:<div className={`cards ${claude?'challenger-cards':''}`}>{active.map((b,i)=><article className="betcard" key={b.game_id+b.player_id+b.book}><div className="cardtop"><span>{String(i+1).padStart(2,'0')} / {claude?'CHALLENGER':'CHAMPION'}</span><strong>{pct(b.ev)} est. EV</strong></div><h3>{b.player}</h3><p>{b.team} vs {b.opponent} · {date(b.kickoff)} ET</p><div className="offer"><strong>{b.side} {b.line}</strong><span>{odds(b.odds)}<small>{b.book}</small></span></div><div className="cardmetrics"><div><span>Model mean</span><b>{b.mean.toFixed(1)}</b></div><div><span>Win probability</span><b>{pct(b.p_final)}</b></div><div><span>Bet to · {claude?'2':'3'}% EV</span><b>{odds(b.bet_to)}</b></div></div><p className="explain">{claude?'Claude blends 35% of its mean difference beyond a 1.5-attempt dead zone. Its market center uses different lines and includes the target book.':`Model probability weight ${pct(b.model_weight??.5)}. EV after a 2-point miss: ${pct(b.robust_ev??0)}.`}</p>{b.expected_margin!==undefined&&<p className="explain">{b.team} {spread(-b.expected_margin)} · Game total {b.game_total}.{b.scenario_means&&<> Pregame spread sensitivity: {b.scenario_means.underdog_7.toFixed(1)} attempts as a 7-point underdog; {b.scenario_means.favorite_7.toFixed(1)} as a 7-point favorite.</>}</p>}{!!b.warnings?.length&&<p className="explain">{b.warnings.join(' · ')}</p>}<a href={b.source_url} target="_blank" rel="noreferrer">Check current sportsbook prices ↗</a></article>)}</div>}
 <div className="notice">{claude?<><strong>Claude model, shared execution checks.</strong> Its forecast, residual shape, saved QB corrections, and betting thresholds are preserved. This integration adds the same event, freshness, starting-role and injury checks used for Codex. Coefficients refit as new games arrive; launch residuals and QB corrections remain frozen to avoid the original refit bug.</>:<><strong>Prospective evaluation.</strong> EV is estimated, not a verified return. Codex’s blending weights remain provisional.</>} Confirm the current sportsbook line and price. The bet-to number alone does not recheck eligibility.</div>
 <div className="sectiontitle"><h2>All evaluated quarterbacks</h2><span>{claude?'Highest-EV offer per QB · native policy holds included':'Best qualifying offer first · holds included'}</span></div>
 <div className="tablewrap"><Table><TableHeader><TableRow><TableHead>Quarterback / matchup</TableHead><TableHead>Offer</TableHead><TableHead>Model mean</TableHead><TableHead>Model / market / final</TableHead><TableHead>Est. EV</TableHead><TableHead>Decision</TableHead></TableRow></TableHeader><TableBody>{model.watchlist.map(b=><TableRow key={b.game_id+b.player_id}><TableCell><strong>{b.player}</strong><small>{b.team} vs {b.opponent} · {date(b.kickoff)} ET</small></TableCell><TableCell>{b.side} {b.line} · {odds(b.odds)}<small>{b.book}</small></TableCell><TableCell>{b.mean.toFixed(1)}{b.interval80&&<small>80% interval {b.interval80.map(Math.round).join('–')}</small>}{b.expected_margin!==undefined&&<small>{b.team} {spread(-b.expected_margin)} · Total {b.game_total}</small>}</TableCell><TableCell>{pct(b.p_model)} / {pct(b.p_market)}<small>Final {pct(b.p_final)} on {b.side.toLowerCase()}</small></TableCell><TableCell className={b.ev>0?'positive':''}>{pct(b.ev)}</TableCell><TableCell><span className={`decision ${b.status==='qualified'?'qualified':''}`}>{new Date(b.kickoff).getTime()<=now?'Started':blocked?'Suspended':b.status}</span><small>{b.reasons?.join(' · ')||'All checks passed'}</small>{!!b.warnings?.length&&<small>{b.warnings.join(' · ')}</small>}</TableCell></TableRow>)}</TableBody></Table></div>
 </>;
}

function ComparisonPanel({board}:{board:Board|null}){
 const c=board?.comparison;const metrics=c?.forecast_metrics;const historical=c?.historical_benchmark;
 return <>
 <div className="sectiontitle"><h2>Prospective scorecard</h2><span>Starts when both models run together</span></div>
 <div className="notice">Separate first decisions, flat one-unit returns, and the same exact-event closing-price rules. Codex’s earlier solo picks are excluded from this comparison. Different bet counts reflect each policy; neither is forced to copy the other.</div>
 <div className="tablewrap"><Table><TableHeader><TableRow><TableHead>Model</TableHead><TableHead>Recorded / settled bets</TableHead><TableHead>Return / ROI</TableHead><TableHead>Mean price CLV</TableHead><TableHead>Paired forecast MAE</TableHead><TableHead>Brier / log loss</TableHead></TableRow></TableHeader><TableBody>{(['champion','challenger'] as const).map(k=>{const p=c?.performance[k],m=metrics?.[k];return <TableRow key={k}><TableCell>{k==='champion'?'Codex V2':'Claude Fable'}</TableCell><TableCell>{p?.bets??0} / {p?.settled??0}</TableCell><TableCell>{p?.settled?`${value(p.units,2)}u / ${p.roi==null?'—':pct(p.roi)}`:'—'}</TableCell><TableCell>{p?.mean_clv==null?'—':pct(p.mean_clv)}<small>{p?.clv_bets??0} captured closes</small></TableCell><TableCell>{value(m?.mae)}</TableCell><TableCell>{value(m?.brier)} / {value(m?.log_loss)}</TableCell></TableRow>})}</TableBody></Table></div>
 <p className="notice">{metrics?.n_settled??0} paired QB outcomes; {metrics?.n_probability_scored??0} scored at a common offered line. Calibration uses the first shared snapshot and a deterministic book/line choice, including held offers. Pushes are excluded from the conditional over-probability scores. Fewer errors and lower Brier/log loss are better; no winner is declared from a small sample.</p>
 <div className="sectiontitle"><h2>Same offer, two forecasts</h2><span>{c?.paired_forecasts.length??0} paired quarterbacks · final over probabilities</span></div>
 <div className="tablewrap"><Table><TableHeader><TableRow><TableHead>Quarterback</TableHead><TableHead>Common reference offer</TableHead><TableHead>Codex mean / P(over)</TableHead><TableHead>Claude mean / P(over)</TableHead><TableHead>Probability difference</TableHead></TableRow></TableHeader><TableBody>{(c?.paired_forecasts??[]).map(p=><TableRow key={p.game_id+p.player_id}><TableCell>{p.player}<small>{p.team} · {date(p.kickoff)} ET</small></TableCell><TableCell>{p.line} attempts<small>{p.book}</small></TableCell><TableCell>{p.champion.mean.toFixed(1)} / {pct(p.champion.p_over)}</TableCell><TableCell>{p.challenger.mean.toFixed(1)} / {pct(p.challenger.p_over)}</TableCell><TableCell>{((p.challenger.p_over-p.champion.p_over)*100).toFixed(1)} points<small>Claude minus Codex</small></TableCell></TableRow>)}</TableBody></Table></div>
 <section className="method"><div><div className="eyebrow">SAME HISTORICAL GAMES</div><h2>Small difference. Still an open contest.</h2><p>On {historical?.n??537} identical 2025 QB-games, Claude MAE was {value(historical?.claude.mae??6.6826,2)} and Codex MAE was {value(historical?.astra.mae??6.7238,2)}. The difference is statistically uncertain. Seven zero-attempt rows explain much of the larger gap between the original headline figures.</p><p>Both policies have seen 2025 results. This is exposed historical evidence. The prospective scorecard above provides the new test.</p></div><div className="validation"><h3>What the review found</h3><p>Claude’s historical odds archive and cross-line market center are useful advances. Its published ROI, however, uses a different probability distribution and portfolio from its live card, and most 2025 quote updates occur after scheduled kickoff. That does not establish pregame execution.</p><p>The integration preserves Claude’s model and policy, while isolating source and season-update repairs. <a href={`${source}/blob/main/research/CLAUDE_REVIEW.md`}>Read the full comparison and critiques ↗</a></p></div></section>
 </>;
}

export default function Home(){
 const [board,setBoard]=useState<Board|null>(null);const [error,setError]=useState(false);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const load=()=>{setNow(Date.now());fetch(`https://raw.githubusercontent.com/drhyphy/nfl-qb-attempts/main/data/published/latest.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).catch(()=>fetch('./board.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()})).then(x=>{setBoard(x);setError(false)}).catch(()=>setError(true));};load();const id=setInterval(load,60000);return()=>clearInterval(id);},[]);
 const stale=!!board&&now-new Date(board.generated_at).getTime()>26*3600000;
 const failed=error||board?.status==='source_failure';
 const count=(rows:Bet[])=>rows.filter(b=>new Date(b.kickoff).getTime()>now).length;
 const claude=board?.challenger;
 return <main><header className="masthead"><a className="wordmark" href="#">ATTEMPTS<span>/ NFL</span></a><span className="edition">CHAMPION + CHALLENGER</span><a href={source} target="_blank" rel="noreferrer">Source & record ↗</a></header>
 <section className="intro"><div><div className="eyebrow">{board?.slate??'NFL REGULAR SEASON'}</div><h1>Quarterback pass attempts.</h1><p>Codex V2 and Claude Fable · one shared morning snapshot.</p></div><div className="run"><span className={`dot ${stale||failed?'amber':''}`}/><strong>{failed?'Source unavailable':stale?'Update overdue':board?'Latest model board':'Loading current board'}</strong><p>{board?`${date(board.generated_at)} ET`:'Retrieving the latest evaluation'}</p><small>Scheduled daily · 6:30 a.m. Eastern · delays possible</small></div></section>
 <div className="stats"><div><span>Codex qualified bets</span><strong>{board&&!failed&&!stale?count(board.recommendations):'—'}</strong></div><div><span>Claude qualified bets</span><strong>{claude?.status==='ok'&&!failed&&!stale?count(claude.recommendations):'—'}</strong></div><div><span>Quarterbacks / book quotes</span><strong>{board?`${board.players} / ${board.quotes}`:'—'}</strong></div><div><span>Paired settled forecasts</span><strong>{board?.comparison?.forecast_metrics.n_settled??0}</strong></div></div>
 {failed&&<div role="alert" className="notice">The latest collection failed. Recommendations are suspended; see the data notes below.</div>}{stale&&<div role="alert" className="notice">This board is overdue. Recommendations are suspended until a fresh evaluation arrives.</div>}
 <Tabs defaultValue="champion" className="modeltabs"><TabsList variant="line"><TabsTrigger value="champion">Codex V2</TabsTrigger><TabsTrigger value="challenger">Claude challenger</TabsTrigger><TabsTrigger value="comparison">Head to head</TabsTrigger></TabsList><TabsContent value="champion"><ModelPanel kind="champion" model={board??{status:'loading',recommendations:[],watchlist:[]}} now={now} suspended={stale||failed||!board}/></TabsContent><TabsContent value="challenger"><ModelPanel kind="challenger" model={claude??{status:'unavailable',recommendations:[],watchlist:[]}} now={now} suspended={stale||failed||!board}/></TabsContent><TabsContent value="comparison"><ComparisonPanel board={board}/></TabsContent></Tabs>
 {!!claude?.source_errors?.length&&<details><summary>Challenger data notes ({claude.source_errors.length})</summary>{claude.source_errors.map((s,i)=><p key={i}>{s}</p>)}</details>}
 {!!board?.source_errors?.length&&<details><summary>Shared data notes ({board.source_errors.length})</summary>{board.source_errors.map((s,i)=><p key={i}>{s}</p>)}</details>}
 <footer><span>ATTEMPTS / {board?.model_version??'v2'} · NFL</span><span><a href={`${source}/blob/main/research/MODEL_CARD.md`}>Codex method</a> · <a href={`${source}/blob/main/research/CLAUDE_REVIEW.md`}>Claude review</a> · <a href={`${source}/tree/main/challenger`}>Challenger provenance</a></span><span>Public data: nflverse · ScoresAndOdds · ESPN</span></footer>
 </main>;
}
