'use client';
import {useEffect,useState} from 'react';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';

type Bet={player:string;team:string;opponent:string;side:string;line:number;book:string;odds:number;mean:number;p_model:number;p_market:number;p_final:number;ev:number;robust_ev:number;bet_to:number;status:string;reasons:string[];kickoff:string;source_url:string;observed_at:string;other_books:number;interval80:number[];expected_margin?:number;game_total?:number;model_weight?:number;warnings?:string[];scenario_means?:{underdog_7:number;pickem:number;favorite_7:number};script_shares?:{leading:number;close:number;trailing:number}};
type Board={generated_at:string;status:string;slate:string;quotes:number;players:number;recommendations:Bet[];watchlist:Bet[];source_errors:string[];validation?:{chosen:string;holdout_2025:{mae:number;rmse:number;coverage_80:number};baseline_2025:{mae:number};market_edge_validated:boolean};performance?:{bets:number;settled:number;units:number;roi:number|null};model_version:string};
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const spread=(n:number)=>n===0?'PK':`${n>0?'+':''}${n}`;
const odds=(n:number)=>n>0?`+${n}`:String(n);
const date=(d:string)=>new Date(d).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export default function Home(){
 const [board,setBoard]=useState<Board|null>(null);const [error,setError]=useState(false);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const load=()=>{setNow(Date.now());fetch(`https://raw.githubusercontent.com/drhyphy/nfl-qb-attempts/main/data/published/latest.json?t=${Date.now()}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>{setBoard(x);setError(false)}).catch(()=>fetch('./board.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setBoard).catch(()=>setError(true)));};load();const id=setInterval(load,60000);return()=>clearInterval(id);},[]);
 const stale=!!board&&now-new Date(board.generated_at).getTime()>26*3600000;
 const failed=error||board?.status==='source_failure';
 const active=(board?.recommendations??[]).filter(b=>new Date(b.kickoff).getTime()>now);
 return <main><header className="masthead"><a className="wordmark" href="#">ATTEMPTS<span>/ NFL</span></a><span className="edition">DAILY MODEL BOARD</span><a href="https://github.com/drhyphy/nfl-qb-attempts" target="_blank" rel="noreferrer">Source & record ↗</a></header>
 <section className="intro"><div><div className="eyebrow">{board?.slate??'2026 REGULAR SEASON'}</div><h1>Quarterback pass attempts.</h1><p>Best available prices. A measured edge.</p></div><div className="run"><span className={`dot ${stale||error?'amber':''}`}/><strong>{failed?'Source unavailable':stale?'Update overdue':board?'Latest morning board':'Loading current board'}</strong><p>{board?`${date(board.generated_at)} ET`:'Retrieving the latest evaluation'}</p><small>Scheduled daily · 6:30 a.m. Eastern · delays possible</small></div></section>
 <div className="stats"><div><span>Qualified bets</span><strong>{board?active.length:'—'}</strong></div><div><span>Quarterbacks scanned</span><strong>{board?.players??'—'}</strong></div><div><span>Paired book quotes</span><strong>{board?.quotes??'—'}</strong></div><div><span>Live settled bets</span><strong>{board?.performance?.settled??0}</strong></div></div>
 <div className="sectiontitle"><h2>Recommended bets</h2><span>Ranked by stressed expected return</span></div>
 {failed&&<div role="alert" className="notice">The latest collection failed. No bets are actionable; see the data coverage notes below.</div>}
 {stale&&<div role="alert" className="notice">This board is overdue for an update. Recommendations are suspended until a fresh evaluation arrives.</div>}
 {!board?<div className="empty"><span className="emptytag">{error?'SOURCE UNAVAILABLE':'EVALUATING'}</span><h3>{error?'Current odds could not be loaded.':'The first live evaluation is being prepared.'}</h3><p>No recommendations are displayed until prices and model checks are complete.</p></div>:active.length===0||stale||failed?<div className="empty"><span className="emptytag">NO QUALIFYING BETS</span><h3>Waiting for a price worth taking.</h3><p>{stale?'The last evaluation remains visible below for reference.':'No current offer clears the expected-return, price-quality, starting-status, and probability-stress checks. The evaluated candidates are below.'}</p></div>:<div className="cards">{active.map((b,i)=><article className="betcard" key={b.player+b.book}><div className="cardtop"><span>0{i+1} / EXPERIMENTAL EDGE</span><strong>{pct(b.ev)} est. EV</strong></div><h3>{b.player}</h3><p>{b.team} vs {b.opponent} · {date(b.kickoff)} ET</p><div className="offer"><strong>{b.side} {b.line}</strong><span>{odds(b.odds)}<small>{b.book}</small></span></div><div className="cardmetrics"><div><span>Model mean</span><b>{b.mean.toFixed(1)}</b></div><div><span>Win probability</span><b>{pct(b.p_final)}</b></div><div><span>Bet to</span><b>{odds(b.bet_to)}</b></div></div><p className="explain">{b.other_books} other books inform the market estimate. EV after a 2-point probability miss: {pct(b.robust_ev)}. Model weight {pct(b.model_weight??.5)}.</p>{b.expected_margin!==undefined&&<p className="explain">{b.team} {spread(-b.expected_margin)} · Game total {b.game_total}. Pregame spread sensitivity, other inputs fixed: {b.scenario_means?.underdog_7.toFixed(1)} attempts as a 7-point underdog; {b.scenario_means?.favorite_7.toFixed(1)} as a 7-point favorite.</p>}{!!b.warnings?.length&&<p className="explain">{b.warnings.join(' · ')}</p>}<a href={b.source_url} target="_blank" rel="noreferrer">Check current sportsbook prices ↗</a></article>)}</div>}
 <div className="notice"><strong>Prospective evaluation.</strong> Estimated EV is a forecast. This model has no verified historical prop-odds ROI. Prices are public comparison-feed observations; confirm the offered line and price before acting.</div>
 <div className="sectiontitle"><h2>Market evaluation</h2><span>Best offer per quarterback · includes held candidates</span></div>
 <div className="tablewrap"><Table><TableHeader><TableRow><TableHead>Quarterback / matchup</TableHead><TableHead>Best offer</TableHead><TableHead>Projection / game state</TableHead><TableHead>Model / market</TableHead><TableHead>Est. EV</TableHead><TableHead>Decision</TableHead></TableRow></TableHeader><TableBody>{(board?.watchlist??[]).map(b=><TableRow key={b.player}><TableCell><strong>{b.player}</strong><small>{b.team} vs {b.opponent} · {date(b.kickoff)} ET</small></TableCell><TableCell>{b.side} {b.line} · {odds(b.odds)}<small>{b.book}</small></TableCell><TableCell>{b.mean.toFixed(1)}<small>80% interval {b.interval80?.map(n=>Math.round(n)).join('–')}</small>{b.expected_margin!==undefined&&<small>{b.team} {spread(-b.expected_margin)} · Total {b.game_total}</small>}</TableCell><TableCell>{pct(b.p_model)} / {pct(b.p_market)}<small>Final {pct(b.p_final)}</small></TableCell><TableCell className={b.ev>0?'positive':''}>{pct(b.ev)}</TableCell><TableCell><span className={`decision ${b.status==='qualified'?'qualified':''}`}>{new Date(b.kickoff).getTime()<=now?'Started':b.status}</span><small>{b.reasons?.join(' · ')||'All checks passed'}</small>{!!b.warnings?.length&&<small>{b.warnings.join(' · ')}</small>}</TableCell></TableRow>)}</TableBody></Table></div>
 <section className="method"><div><div className="eyebrow">BUILT TO BE MEASURED</div><h2>Game state shapes the forecast.</h2><p>Current game spreads and totals enter the independent attempts forecast, with team passing tendencies and QB rushing interactions. More elaborate state-mixture and tendency models were tested; their development gains did not justify replacing the simpler regression.</p><p>The forecast receives 50% weight alongside other-book consensus, or 35% with limited QB history or a team/coach change. Disagreement alone does not block a bet. Qualification requires at least 3% blended EV, positive independent-model EV, and positive EV after a 2-point probability miss. These weights are provisional. Every recommendation and alternative blend is archived before kickoff.</p></div><div className="validation"><h3>Exposed 2025 benchmark</h3><dl><div><dt>Selected model</dt><dd>{board?.validation?.chosen??'Evaluating'}</dd></div><div><dt>Average absolute error</dt><dd>{board?.validation?`${board.validation.holdout_2025.mae.toFixed(2)} attempts`:'—'}</dd></div><div><dt>Frozen V1 baseline</dt><dd>{board?.validation?`${board.validation.baseline_2025.mae.toFixed(2)} attempts`:'—'}</dd></div><div><dt>80% interval coverage</dt><dd>{board?.validation?pct(board.validation.holdout_2025.coverage_80):'—'}</dd></div></dl><p>The improvement over V1 is small and statistically uncertain. Historical game odds are closing references, not archived morning prices. 2025 was already examined; 2026 provides the prospective test.</p></div></section>
 {(board?.source_errors?.length??0)>0&&<details><summary>Data coverage notes ({board?.source_errors.length})</summary>{board?.source_errors.map((s,i)=><p key={i}>{s}</p>)}</details>}
 <footer><span>ATTEMPTS / {board?.model_version??'v2'} · NFL</span><span>Public data: <a href="https://nflreadr.nflverse.com/articles/nflverse_data_schedule.html">nflverse</a> · <a href="https://www.scoresandodds.com/nfl/props/pass-attempts">ScoresAndOdds</a></span><a href="https://github.com/drhyphy/nfl-qb-attempts/blob/main/research/MODEL_CARD.md">Method & limitations ↗</a></footer>
 </main>;
}
